#!/usr/bin/env bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

unmount_usb() {
  if mountpoint -q /mnt/usb; then
    sudo umount /mnt/usb
    echo -e "${GREEN}USB drive unmounted.${NC}"
  fi
}

mount_usb() {
  if mountpoint -q /mnt/usb; then
    echo -e "${GREEN}USB drive already mounted.${NC}"
  else
    device_found=false
    for dev in sda sdb sdc sdd sde sdf; do
      if sudo blkid /dev/"$dev" | grep -iq 'TYPE="vfat"'; then
        device_found=true
        mkdir -p /mnt/usb
        sudo mount /dev/"$dev" /mnt/usb && { echo -e "${GREEN}USB drive mounted on /dev/$dev.${NC}"; break; } || echo -e "${RED}Failed to mount /dev/$dev.${NC}"
      fi
    done
    if [ "$device_found" = false ]; then
      echo -e "${RED}No USB devices found.${NC}"
      exit 1
    fi
  fi
}

check_file_exists() {
  if [[ ! -f "$1" ]]; then
    echo -e "${RED}Error: File $1 does not exist.${NC}"
    exit 1
  fi
}

setup_ssh_directory() {
  export SSH_DIR=/root/.ssh
  mkdir -p "$SSH_DIR"
}

copy_keys() {
  check_file_exists "/mnt/usb/id_ed25519_agenix.pub"
  check_file_exists "/mnt/usb/id_ed25519_agenix"
  cp /mnt/usb/id_ed25519_agenix.pub "$SSH_DIR"
  cp /mnt/usb/id_ed25519_agenix "$SSH_DIR"
  chmod 600 "$SSH_DIR"/id_ed25519_agenix{,.pub}
}

set_keys() {
  check_file_exists "/mnt/usb/id_ed25519_github.pub"
  check_file_exists "/mnt/usb/id_ed25519_github"
  cp /mnt/usb/id_ed25519_github.pub "$SSH_DIR/id_ed25519.pub"
  cp /mnt/usb/id_ed25519_github "$SSH_DIR/id_ed25519"
  chmod 600 "$SSH_DIR/id_ed25519"
  chmod 644 "$SSH_DIR/id_ed25519.pub"
}

trap unmount_usb EXIT

setup_ssh_directory
mount_usb
copy_keys
set_keys
unmount_usb

echo -e "${GREEN}Keys copied successfully.${NC}"
