#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Cleaning up old system generations...${NC}"

sudo nix-collect-garbage --delete-older-than 7d

echo -e "${GREEN}Cleanup complete!${NC}"
